---
jobs:
    - name: hello-pipeline
      plan:
        - task: hello-pipeline
          config:
            platform: linux
            image_resource:
              type: docker-image
              source: {repository: busybox}
            run:
              path: echo
              args:
                - hello pipeline
